=== AcademySoftwareFoundation/OpenCue/cuebot/src/test/resources/conf/dtd/cjsl-1.8.dtd
<!-- ================================================================= -->
<!-- SpiCue Job Spec DTD ver 1.8                                       -->
<!-- middle-tier@imageworks.com                                        -->
<!-- ================================================================= -->

<!ELEMENT spec              (facility?,dept?,show,shot,user,email?,uid,job*,depends*)>
<!ELEMENT facility          (#PCDATA)*>
<!ELEMENT dept              (#PCDATA)*>
<!ELEMENT show              (#PCDATA)*>
<!ELEMENT shot              (#PCDATA)*>
<!ELEMENT user              (#PCDATA)*>
<!ELEMENT email             (#PCDATA)*>
<!ELEMENT uid               (#PCDATA)*>

<!-- ================================================================= -->
<!-- Jobs                                                              -->
<!-- ================================================================= -->
<!ELEMENT job               (paused?,maxretries?,autoeat?,localbook?,os?,env*,layers?)>
<!ATTLIST job
    name                    NMTOKEN                 	#REQUIRED
>
<!ELEMENT paused            (#PCDATA)*>
<!ELEMENT maxretries        (#PCDATA)*>
<!ELEMENT autoeat           (#PCDATA)*>
<!ELEMENT os                (#PCDATA)*>
<!ELEMENT localbook         (#PCDATA)*>
<!ATTLIST localbook
    host                    NMTOKEN                     #REQUIRED
    cores                   NMTOKEN                     #REQUIRED
    memory                  NMTOKEN                     #REQUIRED
    threads                 NMTOKEN                     #REQUIRED
    gpu_memory              NMTOKEN                     #REQUIRED
>

<!-- ================================================================= -->
<!-- Layers                                                            -->
<!-- ================================================================= -->

<!ELEMENT layers            (layer+)>
<!ELEMENT layer             (cmd,range,chunk,cores?,gpu?,threadable?,memory?,gpu_memory?,tags?,limits?,env*,services?)>
<!ATTLIST layer
    name                    NMTOKEN                #REQUIRED
    type                    (RENDER | UTIL | POST) #REQUIRED
>
<!ELEMENT cmd               (#PCDATA)*>
<!ELEMENT range             (#PCDATA)*>
<!ELEMENT chunk             (#PCDATA)*>
<!ELEMENT cores             (#PCDATA)*>
<!ELEMENT gpu               (#PCDATA)*>
<!ELEMENT threadable        (#PCDATA)*>
<!ELEMENT memory            (#PCDATA)*>
<!ELEMENT gpu_memory        (#PCDATA)*>
<!ELEMENT tags              (#PCDATA)*>
<!ELEMENT limits            (limit+)>
<!ELEMENT services          (service+)>
<!ELEMENT env               (key*)>


<!-- ================================================================= -->
<!-- Layer Services                                                    -->
<!-- ================================================================= -->
<!ELEMENT service           (#PCDATA)*>

<!-- ================================================================= -->
<!-- Layer Limits                                                    -->
<!-- ================================================================= -->
<!ELEMENT limit           (#PCDATA)*>

<!-- ================================================================= -->
<!-- Environment Variables -->
<!-- ================================================================= -->

<!ELEMENT key              (#PCDATA)*>
<!ATTLIST key
    name                    NMTOKEN                 #REQUIRED
>

<!-- ================================================================= -->
<!-- Dependencies                                                      -->
<!-- ================================================================= -->

<!ELEMENT depends           (depend*)>
<!ELEMENT depend            (depjob,deplayer?,depframe?,onjob,onlayer?,onframe?)>
<!ATTLIST depend
    anyframe               NMTOKEN                  #IMPLIED
    type                   (LAYER_ON_SIM_FRAME|PREVIOUS_FRAME|JOB_ON_JOB|JOB_ON_LAYER|JOB_ON_FRAME|LAYER_ON_JOB|LAYER_ON_FRAME|LAYER_ON_LAYER|FRAME_ON_JOB|FRAME_ON_LAYER|FRAME_ON_FRAME|FRAME_BY_FRAME)   #REQUIRED
>
<!ELEMENT depjob           (#PCDATA)*>
<!ELEMENT onjob            (#PCDATA)*>
<!ELEMENT deplayer         (#PCDATA)*>
<!ELEMENT onlayer          (#PCDATA)*>
<!ELEMENT depframe         (#PCDATA)*>
<!ELEMENT onframe          (#PCDATA)*>

=== AcademySoftwareFoundation/OpenCue/cuebot/src/test/resources/conf/jobspec/jobspec_dispatch_gpu_test.xml
<?xml version="1.0"?>
<!--
   Copyright Contributors to the OpenCue Project

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->




<!DOCTYPE spec SYSTEM "../dtd/cjsl-1.8.dtd">
<spec>

    <facility>spi</facility>
    <dept>Lighting</dept>
    <show>pipe</show>
    <shot>dev.cue</shot>
    <user>middletier</user>
    <uid>9860</uid>

    <job name="pipe-dev.cue-middletier_shell_dispatch_gpu_test_v1">
        <paused>false</paused>
        <layers>

            <layer name="pass_1" type="RENDER">
                <cmd>/shots/pipe/usr_middletier/logs/help.py</cmd>
                <range>1-10</range>
                <chunk>1</chunk>
                <cores>100</cores>
                <memory>2gb</memory>
                <gpu_memory>512m</gpu_memory>
                <tags>general</tags>
                <services>
                    <service>arnold</service>
                </services>
            </layer>

            <layer name="pass_2" type="RENDER">
                <cmd>/shots/pipe/usr_middletier/logs/help.py</cmd>
                <range>1-10</range>
                <chunk>1</chunk>
                <cores>100</cores>
                <memory>2gb</memory>
                <gpu_memory>512m</gpu_memory>
                <tags>general</tags>
                <services>
                    <service>arnold</service>
                </services>
            </layer>

        </layers>
    </job>

    <job name="pipe-dev.cue-middletier_shell_dispatch_gpu_test_v2">
        <paused>false</paused>
        <layers>

            <layer name="pass_1" type="RENDER">
                <cmd>/shots/pipe/usr_middletier/logs/help.py</cmd>
                <range>1-10</range>
                <chunk>1</chunk>
                <cores>100</cores>
                <memory>2gb</memory>
                <gpu_memory>512m</gpu_memory>
                <tags>general</tags>
                <services>
                    <service>prman</service>
                    <service>katana</service>
                </services>
            </layer>
        </layers>
    </job>

</spec>
