=== AcademySoftwareFoundation/OpenCue/cuebot/src/main/resources/public/dtd/cjsl-1.7.dtd
<!-- ================================================================= -->
<!-- SpiCue Job Spec DTD ver 1.7                                       -->
<!-- middle-tier@imageworks.com                                        -->
<!-- ================================================================= -->

<!ELEMENT spec              (facility?,dept?,show,shot,user,email?,uid,job*,depends*)>
<!ELEMENT facility          (#PCDATA)*>
<!ELEMENT dept              (#PCDATA)*>
<!ELEMENT show              (#PCDATA)*>
<!ELEMENT shot              (#PCDATA)*>
<!ELEMENT user              (#PCDATA)*>
<!ELEMENT email             (#PCDATA)*>
<!ELEMENT uid               (#PCDATA)*>

<!-- ================================================================= -->
<!-- Jobs                                                              -->
<!-- ================================================================= -->
<!ELEMENT job               (paused?,maxretries?,autoeat?,os?,env*,layers?)>
<!ATTLIST job
    name                    NMTOKEN                 	#REQUIRED
>
<!ELEMENT paused            (#PCDATA)*>
<!ELEMENT maxretries        (#PCDATA)*>
<!ELEMENT autoeat           (#PCDATA)*>
<!ELEMENT os                (#PCDATA)*>

<!-- ================================================================= -->
<!-- Layers                                                            -->
<!-- ================================================================= -->

<!ELEMENT layers            (layer+)>
<!ELEMENT layer             (cmd,range,chunk,cores?,threadable?,memory?,gpu?,tags?,env*,services?)>
<!ATTLIST layer
    name                    NMTOKEN                #REQUIRED
    type                    (Render | Util | Post) #REQUIRED
>
<!ELEMENT cmd               (#PCDATA)*>
<!ELEMENT range             (#PCDATA)*>
<!ELEMENT chunk             (#PCDATA)*>
<!ELEMENT cores             (#PCDATA)*>
<!ELEMENT threadable        (#PCDATA)*>
<!ELEMENT memory            (#PCDATA)*>
<!ELEMENT gpu               (#PCDATA)*>
<!ELEMENT tags              (#PCDATA)*>
<!ELEMENT services          (service+)>
<!ELEMENT env               (key*)>


<!-- ================================================================= -->
<!-- Layer Services                                                    -->
<!-- ================================================================= -->
<!ELEMENT service           (#PCDATA)*>

<!-- ================================================================= -->
<!-- Environment Variables -->
<!-- ================================================================= -->

<!ELEMENT key              (#PCDATA)*>
<!ATTLIST key
    name                    NMTOKEN                 #REQUIRED
>

<!-- ================================================================= -->
<!-- Dependencies                                                      -->
<!-- ================================================================= -->

<!ELEMENT depends           (depend*)>
<!ELEMENT depend            (depjob,deplayer?,depframe?,onjob,onlayer?,onframe?)>
<!ATTLIST depend
    anyframe               NMTOKEN                  #IMPLIED
    type                   (LayerOnSimFrame|PreviousFrame|JobOnJob|JobOnLayer|JobOnFrame|LayerOnJob|LayerOnFrame|LayerOnLayer|FrameOnJob|FrameOnLayer|FrameOnFrame|FrameByFrame)   #REQUIRED
>
<!ELEMENT depjob           (#PCDATA)*>
<!ELEMENT onjob            (#PCDATA)*>
<!ELEMENT deplayer         (#PCDATA)*>
<!ELEMENT onlayer          (#PCDATA)*>
<!ELEMENT depframe         (#PCDATA)*>
<!ELEMENT onframe          (#PCDATA)*>

=== AcademySoftwareFoundation/OpenCue/cue3bot/src/test/resources/conf/jobspec/jobspec_dispatch_gpu_test.xml
<?xml version="1.0"?>
<!--
   Copyright (c) 2018 Sony Pictures Imageworks Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->




<!DOCTYPE spec SYSTEM "../dtd/cjsl-1.7.dtd">
<spec>

    <facility>spi</facility>
    <dept>Lighting</dept>
    <show>pipe</show>
    <shot>dev.cue</shot>
    <user>middletier</user>
    <uid>9860</uid>

    <job name="pipe-dev.cue-middletier_shell_dispatch_gpu_test_v1">
        <paused>false</paused>
        <layers>

            <layer name="pass_1" type="Render">
                <cmd>/shots/pipe/usr_middletier/logs/help.py</cmd>
                <range>1-10</range>
                <chunk>1</chunk>
                <cores>100</cores>
                <memory>2gb</memory>
                <gpu>512m</gpu>
                <tags>general</tags>
                <services>
                    <service>arnold</service>
                </services>
            </layer>

            <layer name="pass_2" type="Render">
                <cmd>/shots/pipe/usr_middletier/logs/help.py</cmd>
                <range>1-10</range>
                <chunk>1</chunk>
                <cores>100</cores>
                <memory>2gb</memory>
                <gpu>512m</gpu>
                <tags>general</tags>
                <services>
                    <service>arnold</service>
                </services>
            </layer>

        </layers>
    </job>

    <job name="pipe-dev.cue-middletier_shell_dispatch_gpu_test_v2">
        <paused>false</paused>
        <layers>

            <layer name="pass_1" type="Render">
                <cmd>/shots/pipe/usr_middletier/logs/help.py</cmd>
                <range>1-10</range>
                <chunk>1</chunk>
                <cores>100</cores>
                <memory>2gb</memory>
                <gpu>512m</gpu>
                <tags>general</tags>
                <services>
                    <service>prman</service>
                    <service>katana</service>
                </services>
            </layer>
        </layers>
    </job>

</spec>
